sudo: required
services:
  - docker

before_install: 
  - docker build -t tsa/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run --env-file=./client/env_file tsa/react-test npm test

after_success: 
  - docker build -t tsa/multi-client ./client
  - docker build -t tsa/multi-nginx ./nginx
  - docker build -t tsa/multi-server ./server
  - docker build -t tsa/multi-worker ./worker

  # Log in into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push tsa/multi-client
  - docker push tsa/multi-nginx
  - docker push tsa/multi-server
  - docker push tsa/multi-worker

#deploy:
  #provider: elasticbeanstalk
  #region: us-west-1
  #app: multi-docker
  #env: MultiDocker-env
  #bucket_name: bucket_name
  #bucket-path: docker-multi
  #on: 
    #branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: 
    #secure: $AWS_SECRET_KEY